/**
*
* auto generated by ibatis tools 
*
**/
package ${packageName?replace(".model",".dto")};
/**
* <#if description?exists>${description}</#if>
*/

public class ${className?cap_first}DTO  implements java.io.Serializable {

<#list fields?keys as key >
    private ${fields[key]} ${key};
</#list>

<#list fields?keys as key >
    public ${fields[key]} get${key?cap_first} (){
        return ${key};
    }
    
    public void set${key?cap_first} (${fields[key]} ${key}){
        this.${key} = ${key};
    }
</#list>

}