/**
*
* auto generated by ibatis tools 
*
**/
package ${packageName?replace(".model",".dao")};

import com.woyo.pay.dao.BaseDAO;
import ${packageName}.${className?cap_first};

public interface ${className?cap_first}DAO extends BaseDAO<${className?cap_first}> {
}