/**
*
* auto generated by ibatis tools 
*
**/
package ${packageName?replace(".model",".dao")}.impl;

import ${packageName}.${className?cap_first};
import ${packageName?replace(".model",".dao")}.${className?cap_first}DAO;
import com.woyo.pay.dao.impl.BaseDAOImpl;

public class ${className?cap_first}DAOImpl extends BaseDAOImpl<${className?cap_first}> implements ${className?cap_first}DAO{
}