/**
*
* auto generated by ibatis tools 
*
**/
package ${packageName};
/**
* <#if description?exists>${description}</#if>${tbComment}
*/

public class ${className?cap_first}  implements java.io.Serializable {

<#list fields?keys as key >
    private ${fields[key]} ${key}; //${comments[key]}
</#list>

<#list fields?keys as key >
    public ${fields[key]} get${key?cap_first} (){
        return ${key};
    }
    
    public void set${key?cap_first} (${fields[key]} ${key}){
        this.${key} = ${key};
    }
</#list>

}